llm:
  provider: openai
  api_key: "***your_api_key***"
  base_url: "***your_base_url***"
  model: "***your_model***"    #example_model: "deepseek-ai/DeepSeek-V2.5"
  temperature: 0.3
  max_tokens: 4096
